//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhilipsHueController.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class HueBridge : global::System.Configuration.ApplicationSettingsBase {
        
        private static HueBridge defaultInstance = ((HueBridge)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new HueBridge())));
        
        public static HueBridge Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("y-C4zf2MUG9EStZq5S3WPVGSkGf4kP-PMfxmeh06")]
        public string EstablishedAppKey {
            get {
                return ((string)(this["EstablishedAppKey"]));
            }
            set {
                this["EstablishedAppKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.1.189")]
        public string EstablishedBridgeIp {
            get {
                return ((string)(this["EstablishedBridgeIp"]));
            }
            set {
                this["EstablishedBridgeIp"] = value;
            }
        }
    }
}
